# docker-compose.yml
services:
  yolov9:
    build:
      context: .  # Directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of your Dockerfile
    container_name: yolov9
    restart: unless-stopped
    runtime: nvidia  # Use NVIDIA runtime for GPU support
    shm_size: '24g'  # Set shared memory size to 64GB
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible to the container
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM_PLUGIN_PATH=/opt/conda/lib/python3.8/site-packages/cv2/qt/plugins
      - QT_QPA_PLATFORM=xcb
    devices:
      - "/dev/ttyS3:/dev/ttyS3"  # Map the host COM port to the container (adjust ttyS3 as needed)
    volumes:
      # - ./dataset/:/coco/  # Mount the local COCO dataset path
      - ./:/yolov9  # Mount the local code directory
      # - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 socket for GUI
      - ./onepose_weights:/opt/conda/lib/python3.8/site-packages/onepose/models/weights
      - ./weight:/yolov9/weight
      - /home/hkuit/git/hkuit-analysis-api/media:/yolov9/media
    working_dir: /yolov9  # Set working directory inside container
    stdin_open: true  # Equivalent to `-i` to keep STDIN open
    tty: true  # Allocate a pseudo-TTY